version: '3.8'

services:
  ts-node-docker:
    ports:
      - "3000:3000"
    build:
      target: production
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/database
    volumes:
      - .:/usr/src/app
    command: node dist/server.js

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: