version: '3.8'

services:
  ts-node-docker:
    ports:
      - "3000:3000"
    build:
      target: production
    depends_on:
      - mongo
      - influxdb
    environment:
      - MONGODB_URI=mongodb://mongo:27017/database
    volumes:
      - .:/usr/src/app
    command: node dist/server.js

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  influxdb:
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=Yellow
      - DOCKER_INFLUXDB_INIT_BUCKET=YellowBucket
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  mongo-data:
  influxdb-data: